### ISSUE TITLE
Can't open .xlsx file after upgrading to 1.2.2

### ISSUE THREAD

**Issue by pzabrocki** [kartik-v/yii2-export#43]
This used to work but after update I can't open generated .xlsx file:

   echo ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
    ]);

Other formats works as expected.
Any ideas?
Thanks

**Comment by kartik-v** [comment]
It works on the demo pages... you may want to check if you have any issues with non updated packages, or some issues with CSS assets, or caching issues on your environment.

**Comment by pzabrocki** [comment]
It started working after downgrading to 1.2.1.
I'll get back to it later.
Thanks

**Comment by antoniomadrigal10** [comment]
I have a problem with xlsx, its not opening the file, it says its corrupt, any ideas? v1.2.2

ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'target'=> ExportMenu::TARGET_BLANK,
                'dropdownOptions' => [
                    'label' => 'Descargar Datos',
                    'class' => 'btn btn-default',

                ],
                'fontAwesome' => false,
                'emptyText'=> 'No se encontraron datos',
                'showConfirmAlert'=>false,
                'exportConfig' => [
                    ExportMenu::FORMAT_HTML => false,
                    ExportMenu::FORMAT_CSV => false,
                    ExportMenu::FORMAT_TEXT => false,
                    ExportMenu::FORMAT_PDF => false,
                    ExportMenu::FORMAT_EXCEL => false
                ],
                'columns' => [
                    [
                        'attribute' => 'id',
                        'value' => 'id',
                        'contentOptions' => ['style'=>'width:80px;'],
                    ],
                    [
                        'attribute' => 'codigo',
                        'value' => 'entrada.producto.codigo',
                        'contentOptions' => ['style'=>'width:150px;'],
                    ],
                    [
                        'attribute' => 'producto',
                        'value' => 'entrada.producto.nombre',
                        'contentOptions' => ['style'=>'width:150px;'],
                    ],
                    [
                        'attribute' => 'lote',
                        'value' => 'entrada.lote'
                    ],
                    'num_tarima',

                    [
                        'attribute' => 'factura',
                        'value' => 'entrada.factura'
                    ],
                    [
                        'attribute' => 'entrada',
                        'value' => 'entrada.id'
                    ],
                    [
                        'attribute' => 'pedido',
                        'value' => 'entrada.pedimiento'
                    ],

                    'cajas',
                    'peso',
                    [
                        'attribute' => 'factura',
                        'value' => 'entrada.factura'
                    ],
                    [
                        'attribute' => 'retenido',
                        'format' => 'html',
                        'value' => function ($model) {
                            if ($model->retenido === $model::NO_RETENIDO) {
                                $class = 'label-success';
                            } elseif ($model->retenido === $model::RETENIDO) {
                                $class = 'label-danger';
                            }

                            return '<span class="label ' . $class . '">' . $model->getRetenidoLabel() . '</span>';
                        },
                        'filter' => Html::activeDropDownList(
                            $searchModel,
                            'retenido',
                            Inventario::getArrayRetenido(),
                            ['class' => 'form-control', 'prompt' => Yii::t('app', 'Todos')]
                        )
                    ],

                ],
             ]);

**Comment by kartik-v** [comment]
There are not many changes in 1.2.2. --- the only related change which may impact is PR #40.

Can you check on your environment by commenting lines 280 and 282 and just retain [line 281](https://github.com/kartik-v/yii2-export/blob/master/ExportMenu.php#L581) and update if that resolves your issue.

**Comment by kartik-v** [comment]
There are not many changes in 1.2.2. --- the only related change which may impact is PR #40. 

However this PR does not impact the demo pages - and excel exports work well.

Can you check on your environment by commenting lines 280 and 282 and just retain [line 281](https://github.com/kartik-v/yii2-export/blob/master/ExportMenu.php#L581) and update if that resolves your issue.

**Comment by kartik-v** [comment]
There are not many changes in 1.2.2. --- the only related change which may impact is PR #40. 

However this PR does not impact the demo pages - and excel exports work well.

Can you check on your environment by commenting lines 580 and 582 and just retain [line 581](https://github.com/kartik-v/yii2-export/blob/master/ExportMenu.php#L581) and update if that resolves your issue.

**Comment by kartik-v** [comment]
Anyway I am noting an enhancement to configure PR #40 better

**Comment by pzabrocki** [comment]
This is it. Commenting lines 580 and 582 helps

**Comment by kartik-v** [comment]
Ok ... I provided a fix that should solve it...

**Comment by macrawat** [comment]
Export to excel 2007+ shows Error code: ERR_INVALID_RESPONSE with Label as Webpage not available.
 I tried commenting line 580 & 582 then it shows:- 
Call to undefined method PHPExcel_Writer_Excel2007::setDelimiter()
Setting  public $clearBuffers = true; also not solved my problem.
I watch your demo page where it's working fine, then what would be the problem with my code ??

**Comment by AndreyHoha** [comment]
I had same problem.

I see in \phpoffice\phpexcel\Classes\PHPExcel\Shared\File.php
	public static function sys_get_temp_dir()
	{
		if (self::$_useUploadTempDirectory) {
			if (ini_get('upload_tmp_dir') !== FALSE) {

Then i set:
\PHPExcel_Shared_File::setUseUploadTempDirectory(true);
before
$writer->save('php://output');
in 
kartik-v\yii2-export\ExportMenu.php

Dont forget set Rigths for upload_tmp_dir .

**Comment by bnu56** [comment]
For others facing this problem, maybe you have the "php-xml" package missing on your server. this was my case.

**Comment by nagaokashi** [comment]
I had same problem. The export menu works fine on local and heroku.com server too. But after upload to godaddy server, Export to excel 2007+ shows Error code: ERR_INVALID_RESPONSE with Label as Webpage not available.
```

echo ExportMenu::widget([
                    'dataProvider' => $dataProviderQuanLySan,
                    'columns' => $gridColumns,
                    'clearBuffers' => true,
                    'initProvider' => true,
                    'filename' => Yii::t('app','Du_Lieu_Dat_San'),
                    'exportConfig' => [
                        ExportMenu::FORMAT_CSV => false,
                        ExportMenu::FORMAT_HTML=> false,
                        ExportMenu::FORMAT_TEXT => false,
                        ExportMenu::FORMAT_PDF => false,
                        ExportMenu::FORMAT_EXCEL => false,
                        ExportMenu::FORMAT_EXCEL_X => [],
                    ],
                    'columnSelectorOptions' => [
                        'title' => Yii::t('app','Chọn các thông tin cần dữ liệu cần tải'),
                        'class' => 'btn btn-lg btn-default'
                    ],
                    'dropdownOptions' => [
                        'label' => Yii::t('app','Tải về'),
                        'title' => Yii::t('app','Tải data với format đã chọn'),
                        'class' => 'btn btn-lg btn-primary'
                    ],
                    'target' => '_self',
                    'showConfirmAlert' => false,
                    'fontAwesome' => true,
                ]);
```

@AndreyHoha I added \PHPExcel_Shared_File::setUseUploadTempDirectory(true); as you said, but I don't know where to set permission for upload_tmp_dir. Where is upload_tmp_dir ?
